package br.com.dfmachado.listadefilmes.models.connection;

import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author diego.felipe
 */
public class HSQL_Manage {

    private final String CREATE_TABLE_STATUS_FILME;
    private final String CREATE_TABLE_FILME;
    private final String INSERT_DEFAULTS_STATUS_FILME;

    private HSQL_Manage() {
        this.CREATE_TABLE_FILME = "create table filme("
                + "id integer generated by default as identity(start with 1) not null,"
                + "titulo_original varchar(75),"
                + "titulo_traduzido varchar(75),"
                + "data date,"
                + "status int not null,"
                + "constraint pk_fm_id primary key(id),"
                + "constraint fk_st foreign key(status) references status_filme(id));";

        this.CREATE_TABLE_STATUS_FILME = "create table status_filme("
                + "id integer generated by default as identity(start with 1) not null,"
                + "descricao varchar(10) not null,"
                + "constraint pk_st_id primary key(id));";

        this.INSERT_DEFAULTS_STATUS_FILME = "INSERT INTO status_filme(descricao) VALUES"
                + "('baixado'),"
                + "('baixando'),"
                + "('fila');";
    }

    public static void createDatabase(Connection conn) throws SQLException {
        HSQL_Manage manage = new HSQL_Manage();
        conn.createStatement().execute(manage.CREATE_TABLE_STATUS_FILME);
        conn.createStatement().execute(manage.CREATE_TABLE_FILME);
        conn.createStatement().execute(manage.INSERT_DEFAULTS_STATUS_FILME);
    }

    public static boolean isDatabaseExists(String path) {
        File file = new File(path + ".script");
        return file.exists();
    }
}
